Dev of Workout/log button (WIP)
sandeepsuri/workout_application pull request #7
Opened 2023-10-12 02:55 UTC by jimip85

This pull request introduces enhancements to the `Log` component, adding a simple, interactive day tracking feature. The key changes include:

- **Incrementing Days:** Holding the image for 3 seconds increments the day counter.
- **Highlighting of Days:** Highlighted days are displayed with a cyan background and text color.
- **Hold Interaction:** The user interaction of "holding" triggers these changes, adding visual feedback and engagement.

This feature can be used for gamification or tracking progress over time, enhancing the user experience. The code has been tested and works as expected.

2023-10-12 20:12 UTC, sandeepsuri requested changes

2023-10-12 20:12 UTC, sandeepsuri commented on workout-app/src/components/log.tsx
Hey @jimip85, there's an issue with setting the highlighted number. the highlighted number doesn't stay on the day it was highlighted for.

Ex. I press and hold, 1 changes colour. I press and hold to add the second day, day 2 switches colour but day 1 switches back to default. The colour change should remain on that number until the whole number set has been filled so it can restart counting

2023-10-24 20:42 UTC, jimip85 commented on workout-app/src/components/log.tsx
Hey Sunny, I appreciate your input on the issue with the highlighted numbers. However, at this stage, we're primarily focusing on the UI development, and we haven't finalized the backend architecture yet. To maintain a clear separation of concerns and ensure efficient progress, I'm concentrating on the frontend component for now. Once we've made more progress on the UI, we can revisit the backend logic. Thanks for your understanding.

2023-10-24 20:52 UTC, sandeepsuri commented on workout-app/src/components/log.tsx
Hey @jimip85, after our discussion, I concur with the approach you've suggested. I propose that we prioritize finalizing the front-end work initially, followed by the backend. This sequential approach ensures clarity in our development process and will likely enhance our efficiency, as we can channel our focus on one aspect at a time.

2023-10-24 20:52 UTC, sandeepsuri approved these changes
After our discussion, I concur with the approach you've suggested. I propose that we prioritize finalizing the front-end work initially, followed by the backend. This sequential approach ensures clarity in our development process and will likely enhance our efficiency, as we can channel our focus on one aspect at a time.

2023-10-24 20:55 UTC, sandeepsuri approved these changes
After our discussion, I concur with the approach you've suggested. I propose that we prioritize finalizing the front-end work initially, followed by the backend. This sequential approach ensures clarity in our development process and will likely enhance our efficiency, as we can channel our focus on one aspect at a time.

2023-10-24 21:09 UTC, merged